### ISSUE TITLE
Added Multiple time zone

### ISSUE THREAD

**Issue by Disha-Bhuva** [Disha-Bhuva/Digital-clock#1]
Add multiple time zone to digital clock

**Comment by samyaksand** [comment]
Hello, Im interested in working on this. Please assign me this issue.

**Comment by Disha-Bhuva** [comment]
Woah Great i am assigning issue to you

**Comment by HackvistCharm** [comment]
Hii, I would Like to work on this issue, as I have a prior knowledge of web development and I think  I can fix this issue. Can you please assign it to me?

**Comment by Disha-Bhuva** [comment]
Hey hari i would like to assign you issue

**Comment by HackvistCharm** [comment]
I have created [PR](https://github.com/Disha-Bhuva/Digital-clock/pull/3). Please review it.
