### ISSUE TITLE
Change theme

### ISSUE THREAD

**Issue by Disha-Bhuva** [Disha-Bhuva/Digital-clock#2]
Add change theme feature in clock

**Comment by AyushK-101** [comment]
I would like to work on this

**Comment by kevalvavaliya** [comment]
Hey @Disha-Bhuva I am good at web development and making the web ui could you please assign the  issue to me

**Comment by Disha-Bhuva** [comment]
Sure @kevalvavaliya

**Comment by Disha-Bhuva** [comment]
Hey @AyushK-101 I think Keval is perfect match for the issue so Sorry to say i am assigning issue to him.Thanks for showing the interest
